on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang python3 python3-pip git gcc-multilib g++-multilib
          git clone https://github.com/alliedmodders/ambuild
          pip3 install ./ambuild
      - name: Download SDKs
        run: |
          git clone --recursive https://github.com/alliedmodders/sourcemod --branch 1.11-dev sourcemod
          git clone https://github.com/alliedmodders/metamod-source --branch master mmsource
      - name: Configure & build
        run: |
          mkdir build && cd build
          CC=clang CXX=clang++ python3 ../configure.py --enable-optimize --sm-path=../sourcemod --mms-path=../mmsource
          ambuild
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: closestpos-linux
          path: build/package/
